modLoader="javafml"
loaderVersion="[36,)"
license="Public domain"

[[mods]]
modId="stationarysourceblocks"
version="1.1.1"
displayName="Stationary Source Blocks"
authors="StephenBarnes, Team Potato"
description='''
Buckets can be filled and emptied, but cannot remove or place source blocks of water or lava.
'''